### ISSUE TITLE
Kernel error for running example.py

### ISSUE THREAD

**Issue by zhuole1025** [mit-han-lab/nunchaku#1]
Hi, thanks for this amazing work! When running the given example, I got the following error: `RuntimeError: CUDA error: no kernel image is available for execution on the device (at /data/nunchaku/src/kernels/awq/gemv_awq.cu:312)`. I have followed the instructions for installation using torch 2.4.1.

**Comment by sxtyzhangzk** [comment]
Hi, may I ask which GPU you are using? We currently support **sm_86 (Ampere, RTX3090/A6000)** and **sm_89 (Ada, RTX4090)**. The kernel may run on sm_80 (A100) but expect a significant performance drop. If you want to try it on A100 you could edit `setup.py` and change `arch=compute_86,code=sm_86` to `arch=compute_80,code=sm_80`.
Unfortunately, we don't support Turing (RTX20 series) and earlier architectures since we depend on FlashAttention. Hopper (H100) also does not work due to the lack of INT4 TensorCore.

**Comment by zhuole1025** [comment]
Thanks for your explanation. Such a pity since I am using H100..

**Comment by Ph0rk0z** [comment]
Can you add an option for xformers or SDPA? If you used the AWQ kernel that supports older cards that's all it would take. Are the weights just standard gemmv or is it custom?

**Comment by bghira** [comment]
may as well use a different inference engine if you're talking about using more generic kernels.

**Comment by Ph0rk0z** [comment]
There aren't a lot of kernels to choose from sadly. Custom kernels seem like the way to go for these transformer based models just like on the LLM side. Unfortunately everyone is using ampere only as the baseline. AWQ does have kernels working for previous implementations and there are other attention mechanisms.

**Comment by gothxx** [comment]
does it support A10?

**Comment by gantuo** [comment]
> Hi, may I ask which GPU you are using? We currently support **sm_86 (Ampere, RTX3090/A6000)** and **sm_89 (Ada, RTX4090)**. The kernel may run on sm_80 (A100) but expect a significant performance drop. If you want to try it on A100 you could edit `setup.py` and change `arch=compute_86,code=sm_86` to `arch=compute_80,code=sm_80`. Unfortunately, we don't support Turing (RTX20 series) and earlier architectures since we depend on FlashAttention. Hopper (H100) also does not work due to the lack of INT4 TensorCore.

Any plan to support Hopper(H100 or H800)?

**Comment by lmxyy** [comment]
> does it support A10?

Yeah

**Comment by lmxyy** [comment]
> > Hi, may I ask which GPU you are using? We currently support **sm_86 (Ampere, RTX3090/A6000)** and **sm_89 (Ada, RTX4090)**. The kernel may run on sm_80 (A100) but expect a significant performance drop. If you want to try it on A100 you could edit `setup.py` and change `arch=compute_86,code=sm_86` to `arch=compute_80,code=sm_80`. Unfortunately, we don't support Turing (RTX20 series) and earlier architectures since we depend on FlashAttention. Hopper (H100) also does not work due to the lack of INT4 TensorCore.
> 
> Any plan to support Hopper(H100 or H800)?

Hopper does not 4-bit tensorcores. We do not have plans to support them due to the hardware constraints.

**Comment by xhj444** [comment]
I am looking forward to supporting the Intel A750 770 graphics card
