### ISSUE TITLE
Can you share your create svdq-int4-flux.1-dev.safetensors script?

### ISSUE THREAD

**Issue by chuck-ma** [mit-han-lab/nunchaku#10]
Hi, thanks for your work. But I'm wondering how to create an int4 model like svdq-int4-flux.1-dev.safetensors, because I have a model fine-tuned from the dev model.

**Comment by chuck-ma** [comment]
Gotcha, it seems that i should use deepcompressor to create w4a4 quantized model

**Comment by zzz11223345** [comment]
> @chuck-ma was wondering if you managed to load the quantization results from deepcompressor to nunchaku, because I got scaler.pt, smooth.pt, ... as a result and not sure how to convert it to nunchaku format.

Hello，I have the same problem, have you solved it?

**Comment by zzz11223345** [comment]
> @chuck-ma was wondering if you managed to load the quantization results from deepcompressor to nunchaku, because I got scaler.pt, smooth.pt, ... as a result and not sure how to convert it to nunchaku format.
@ZukaChilachava Hello, I have the same question, have you solved it?

**Comment by ZukaChilachava** [comment]
@zzz11223345 Here is the response from the devs. https://github.com/mit-han-lab/deepcompressor/issues/27#issuecomment-2498613301

**Comment by batuhan-ince** [comment]
> @chuck-ma was wondering if you managed to load the quantization results from deepcompressor to nunchaku, because I got scaler.pt, smooth.pt, ... as a result and not sure how to convert it to nunchaku format.

Hey @ZukaChilachava, I quantized my fine-tuned flux model, but my model.pt (22GB) is bigger than my fine-tuned model (12GB). Is your files just like that or am I missing something. I did the exactly same things in the README.md. Also @lmxyy can you give me your thougths about this?
