### ISSUE TITLE
How much VRAM is needed

### ISSUE THREAD

**Issue by nitinmukesh** [mit-han-lab/nunchaku#17]
![image](https://github.com/user-attachments/assets/38519d54-c064-4cf6-9c66-00acdd03b4b7)

I thought it will work easily on total 15 GB (8 + 8 shared). Did I misread a and b

**Comment by sxtyzhangzk** [comment]
This figure only lists the memory of DiT. The end-to-end pipeline of flux needs extra memory for the text encoders (mainly T5, 4.6B ~= 9.2GB memory) and VAE (3-4GB memory). 

We could do CPU offloading to save memory, you may try the following example:

```python
import torch

from nunchaku.pipelines import flux as nunchaku_flux

pipeline = nunchaku_flux.from_pretrained(
    "black-forest-labs/FLUX.1-schnell",
    torch_dtype=torch.bfloat16,
    qmodel_path="mit-han-lab/svdquant-models/svdq-int4-flux.1-schnell.safetensors",  # download from Huggingface
)

pipeline.enable_sequential_cpu_offload()

image = pipeline("A cat holding a sign that says hello world", num_inference_steps=4, guidance_scale=0).images[0]
image.save("example.png")
```

Currently, CPU offloading does not affect the DiT layers implemented in Nunchaku. Our experiment shows that the peak GPU memory is around 9GiB. We plan to implement CPU offloading in Nunchaku in our future release to further save the memory.

It is worth mentioning that CPU offloading needs to move weights between CPU and GPU, so you might need more CPU memory. If you only have 16GB CPU memory it might still be challenging.

**Comment by nitinmukesh** [comment]
@sxtyzhangzk 

You are awesome. Works good.

100%|███████████████████████████████████████████████████████████████████████████████████| 4/4 [00:07<00:00,  1.78s/it]

![example](https://github.com/user-attachments/assets/6738a3ac-c185-46c1-8e05-dd15439f76b2)
