### ISSUE TITLE
getting blurred output using Dev model

### ISSUE THREAD

**Issue by nitinmukesh** [mit-han-lab/nunchaku#21]
Please suggest what settings will work best with Dev model

prompt="Northern lights dancing over a snow-covered forest, starry night sky, lone wolf howling, moonlight casting blue shadows, digital art",
width=1024,
height=1024,
num_inference_steps=4,
guidance_scale=0,

![Northern_lights_20241113-171945_813819672](https://github.com/user-attachments/assets/b474f256-a2ac-42ec-932a-e2b2d79b8099)

With 10 steps
![Northern_lights_20241113-173529_261419748](https://github.com/user-attachments/assets/068e5e72-6845-4ea3-993e-68befac7afa8)

==================================================================
With schnell, it's better using the same settings

![Northern_lights_20241113-150307_601342558](https://github.com/user-attachments/assets/eee58cf9-8fb6-4ae6-a3bd-6489a36c0f7b)

**Comment by xmfbit** [comment]
For `dev` model, you should increase `num_inference_steps`. Try use `num_inference_steps=50`. [schnell](https://huggingface.co/black-forest-labs/FLUX.1-schnell) is the distilled version, which reduce the inference step to 4.

**Comment by nitinmukesh** [comment]
tried with 50 steps

![Northern_lights_20241113-180816_593369726](https://github.com/user-attachments/assets/82befea8-805b-44f6-8595-8facff43a75d)
