### ISSUE TITLE
Question about the linear layers in FluxSingleTransformerBlock implementation

### ISSUE THREAD

**Issue by SamMaoYS** [mit-han-lab/nunchaku#28]
Hi, Thank you for open-sourcing the SVDQuant project. The work is very impressive, and I truly appreciate the organized and clean codebase you’ve shared.

While exploring the code, I noticed some differences in the implementation of linear layers between the Nunchaku pipeline and the original Flux pipeline. Despite these differences, the image quality generated by the Nunchaku pipeline aligns remarkably well with the original Flux implementation in bf16, which is fantastic. I have a few questions to gain more insight into these design choices.

In [FluxModel.cpp line260](https://github.com/mit-han-lab/nunchaku/blob/9c4797da11c2628ad126333f695fa6808929166d/src/FluxModel.cpp#L260), the attention projection linear layer is defined with shape [dim, dim], and the MLP layer has a shape of [mlp_hidden_dim, dim]. The output can be represented as:

<img width="465" alt="image" src="https://github.com/user-attachments/assets/1d5a3518-6685-485b-bedd-1a1326c1f79a">

In contrast, the original Flux implementation, [layers.py line238](https://github.com/black-forest-labs/flux/blob/7e14a05ed7280f7a34ece612f7324fcc2ec9efbb/src/flux/modules/layers.py#L238) uses a linear layer with shape [dim + mlp_hidden_dim, dim]. The corresponding output can be represented as:
<img width="412" alt="image" src="https://github.com/user-attachments/assets/933d01a3-ca90-4318-810b-ddd1f3707d60">

These two implementations are equivalent only if:
<img width="167" alt="image" src="https://github.com/user-attachments/assets/39602d0e-3d7e-4c35-8a3f-3816b9b5bf31">
and 
<img width="137" alt="image" src="https://github.com/user-attachments/assets/2ed59281-4406-4808-a463-3af3d9c0aaff">

My question is: Is this a characteristic of the pretrained Flux model weights, or is there a specific technique used to reduce the number of parameters during the quantization process?

I sincerely appreiacte your time for considering the question. Congratulations again on this remarkable achievement. I really enjoy the model and exploring the clean codebase you’ve shared.

**Comment by sxtyzhangzk** [comment]
> These two implementations are equivalent only if: <img alt="image" width="167" src="https://private-user-images.githubusercontent.com/36813656/387541933-39602d0e-3d7e-4c35-8a3f-3816b9b5bf31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNDk0ODUsIm5iZiI6MTczMjA0OTE4NSwicGF0aCI6Ii8zNjgxMzY1Ni8zODc1NDE5MzMtMzk2MDJkMGUtM2Q3ZS00YzM1LThhM2YtMzgxNmI5YjViZjMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDIwNDYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlM2IzODQ3ODZmZjI0MGE3NTY0ODA1N2I0ZGMzYjcwODUwMTljMmMxODA3NjA3ZWMzZGNmNjkyZGMzNzU4NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VIAiO_99Qx6HUCM0WU3B96inLdQbN6MlYU4YVGbKKYM"> and <img alt="image" width="137" src="https://private-user-images.githubusercontent.com/36813656/387542035-2ed59281-4406-4808-a463-3af3d9c0aaff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNDk0ODUsIm5iZiI6MTczMjA0OTE4NSwicGF0aCI6Ii8zNjgxMzY1Ni8zODc1NDIwMzUtMmVkNTkyODEtNDQwNi00ODA4LWE0NjMtM2FmM2Q5YzBhYWZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDIwNDYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0NzljYTA5NjIwYmExN2ZjMWVjZmViMzljNzY1ZGUwNTE2N2NhZWE1NjQ5NzM2MjQ1Y2FmNDRlNGNlZWRmMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UH1mOmKl5It55u41mLVD7Esqylcx0ZETQjhLjt1NZis">

This does not seem correct to me. 
We actually split $W=[W_0, W_1]$ and $b=b_0+b_1$, so

$$
output = \begin{bmatrix}
attn & mlp 
\end{bmatrix} * W^T + b
= \begin{bmatrix}
attn & mlp 
\end{bmatrix} * \begin{bmatrix}
W_0^T \\
W_1^T 
\end{bmatrix} + b_0 + b_1 
= ( attn \cdot W_0^T + b_0 ) + ( mlp \cdot W_1^T + b_1 )
$$

**Comment by SamMaoYS** [comment]
Thank you, @sxtyzhangzk, for the clarifications. My bad, I didn’t decompose the weights correctly. Sorry for the silly questions, and I truly appreciate your time and explanations. All the best!
