### ISSUE TITLE
Full model always needed?

### ISSUE THREAD

**Issue by samedii** [mit-han-lab/nunchaku#29]
Is the full model needed before adding the quantization? It would be nice if it wasn't but maybe it's hard to avoid.

At the moment the full model is downloaded when the pipeline is loading even thought I have already prepared the quantized model locally.

**Comment by lmxyy** [comment]
It is not necessary. We will avoid loading it in the next release.

**Comment by Cannerd-Staff-Admin** [comment]
Can we delete the original BFL flux models after the pipeline has loaded? Or are they required for some part of the quantization setup/execution?

**Comment by samedii** [comment]
I could close this but might be good to leave up for others who are wondering until the next release? :)

**Comment by lmxyy** [comment]
> Can we delete the original BFL flux models after the pipeline has loaded? Or are they required for some part of the quantization setup/execution?

Probably not for now. Everytime you load the model, it will redownload the model again.

**Comment by Cannerd-Staff-Admin** [comment]
Confirmed, yes it does :S Great thanks for your work! It's quite impressive!

**Comment by lmxyy** [comment]
We have updated the codebase. Now you do not need to download the original BF16 transformer.

**Comment by vgabbo** [comment]
Sorry to disturb @lmxyy , I have a problem. When I start the example.py, it loads the entire 32gb of ram, goes up with 8gb of swap and then it kills the process. I have downloaded the latest codebase.

I have tried with cpu offload, but it still gives problems. Can you please give me an advise?



import torch

from nunchaku.pipelines import flux as nunchaku_flux

pipeline = nunchaku_flux.from_pretrained(
    "black-forest-labs/FLUX.1-schnell",
    torch_dtype=torch.bfloat16,
    qmodel_path="mit-han-lab/svdq-int4-flux.1-schnell",
    #qmodel_path="mit-han-lab/svdquant-models/svdq-int4-flux.1-schnell.safetensors",  # download from Huggingface
).to("cuda")

pipeline.enable_sequential_cpu_offload()

image = pipeline("A cat holding a sign that says hello world", num_inference_steps=4, guidance_scale=0).images[0]
image.save("example.png")

**Comment by vgabbo** [comment]
@lmxyy thank you for the response! Yes, I will do, thank you for the patience.
