### ISSUE TITLE
Quality comparison: SVDQuant vs GGUF Q4 ?

### ISSUE THREAD

**Issue by marvin-0042** [mit-han-lab/nunchaku#31]
SVDQuant quality is great! the paper compares the quality with NF4, however **GGUF Q4 (Q4_0, Q4_K_S)** is another popular quantization in community and broadly used in ComfyUI with Image Gen model like FLUX.1 and Video Generation Model like Mochi 1. GGUF Q4 FLUX.1-schenell is also ~6.5GB with good quality, and it does not need big inference engine change.

Can we have any quality comparison between SVDQuant vs GGUF Q4 too, on FLUX.1 (and future Mochi 1)?

Today new image/video gen models like FLUX.1 or Mochi 1, community will first try ComfyUI + GGUF Q4 DiT to enable it on consumer GPU, especially low GPU RAM. If we can see SVDQuant is better than GGUF Q4, on FLUX.1 and/or Mochi 1, it will give community much bigger motivation to adopt or prioritize this very novel SVDQuant.

**Comment by johnwick123f** [comment]
@marvin-0042 NF4 is faster than GGUF Q4, but SVDQuant is 3x faster than NF4. Not only that, but it is also better quality then NF4 and should be similar if not better quality than GGUF Q4. It uses the least vram out of the 3 as well I believe.

So, SVDQuant is way faster, uses less vram, and is similar if not better quality than Q4.

**Comment by lmxyy** [comment]
As GGUF does not have support for diffusers, it is not not easy to do a quantitative comparisons. We have not plan for it for now.

**Comment by lmxyy** [comment]
It seems that diffusers has supported GGUF. I can quickly test their models and make a comprehensive comparisons.

**Comment by lmxyy** [comment]
It seems that diffusers has supported GGUF. I can quickly test their models and make a comprehensive comparison.

**Comment by josephrocca** [comment]
Testing the nunchaku comfyui node versus https://github.com/city96/ComfyUI-GGUF I find that SVDQuant is 2x faster. Take this with a pinch of salt because I could have made a mistake while testing.

**Comment by lmxyy** [comment]
> Testing the nunchaku comfyui node versus https://github.com/city96/ComfyUI-GGUF I find that SVDQuant is 2x faster. Take this with a pinch of salt because I could have made a mistake while testing.

@josephrocca SVDQuant is supposed to be faster than GGUF.

**Comment by josephrocca** [comment]
Yep it is - like I said, my testing shows that SVDQuant is 2x faster. I.e. GGUF is half of SVDQuant's speed.
