### ISSUE TITLE
conda install -c conda-forge gxx=11 gcc=11

### ISSUE THREAD

**Issue by lior007** [mit-han-lab/nunchaku#4]
i got PackagesNotFoundError

then i use:
conda search --channel conda-forge gcc
conda search --channel conda-forge gxx

and then (after i got results)
i used:
conda install -c conda-forge gcc=13.2.0=hc382ac0_10
conda install -c conda-forge gxx=13.2.0=hc382ac0_10

its ok?

**Comment by lmxyy** [comment]
I think it should be fine as long as gcc/g++ >= 11

**Comment by lmxyy** [comment]
Since there are no further replies to the issue, I will close it. Feel free to reopen it if the problem persists.
