### ISSUE TITLE
Question about L1 and L2

### ISSUE THREAD

**Issue by jhss** [mit-han-lab/nunchaku#45]
Hello.

According to the paper, L1 and L2 are real number (floating point number).

Did you conduct any experiment to quantize L1 and L2 to integer with SVD-quant?

If you did quantize L1 and L2, did you use tensor-wise quantization or token-wise quantizaton?

If you didn't quantize L1 and L2 to 16-bit int, why do you use floating point instead of integer in 16-bit calculation?

**Comment by lmxyy** [comment]
We did not quantize L1 and L2. We use the FP16 precision instead of INT16 to follow the original precision.
