### ISSUE TITLE
python run_gradio.py

### ISSUE THREAD

**Issue by lior007** [mit-han-lab/nunchaku#5]
i got error

Traceback (most recent call last):
  File "E:\FROM-FOLDER-D\github\nunchaku\app\t2i\run_gradio.py", line 13, in <module>
    from nunchaku.models.safety_checker import SafetyChecker
ModuleNotFoundError: No module named 'nunchaku'

what to do?

**Comment by lmxyy** [comment]
Did you install our `nunchaku` package?
```shell
conda install -c conda-forge gxx=11 gcc=11
git clone https://github.com/mit-han-lab/nunchaku.git
cd nunchaku
git submodule init
git submodule update
pip install -e .
```

**Comment by lmxyy** [comment]
Since there are no further replies to the issue, I will close it. Feel free to reopen it if the problem persists.
