### ISSUE TITLE
We need a more detailed user guide 

### ISSUE THREAD

**Issue by frankyifei** [mit-han-lab/nunchaku#50]
When I was testing with ComfyUI, I found there is a limitation that resolution should be dividable by 128 other wise it will crash ComfyUI, this must be by design, but it is not mentioned anywhere.
Also it seems to work well with Euler sampler and Simple scheduler, I tried to use other samplers they cause ComfyUI to freeze.

**Comment by weihzh** [comment]
> Also it seems to work well with Euler sampler and Simple scheduler, I tried to use other samplers they cause ComfyUI to freeze.
