### ISSUE TITLE
Windows build issues with cutlass v3.3.0 and CUDA 12.6 results in template errros

### ISSUE THREAD

**Issue by ggarra13** [mit-han-lab/nunchaku#54]
Building on Windows from source with CUDA 12.6 and the cutlass v3.3.0 submodule, with git hash:

73edbaaa882c50f22ce1c30bc6c72aca4872f19e

results in template errors, like:

nunchaku\third_party\cutlass\include\cute/atom/mma_traits_sm90_gmma.hpp(280): error C2672: 'stride': no se encontró una función sobrecargada que coincida

**Comment by sxtyzhangzk** [comment]
Hi, 

Does this issue happen with the version in our submodule? [a75b4ac](https://github.com/NVIDIA/cutlass/tree/a75b4ac483166189a45290783cb0a18af5ff0ea5)

Also, please try upgrading MSVC to the latest version. We tested it on Visual Studio 17.11

**Comment by ggarra13** [comment]
> Hi,
> 
> Does this issue happen with the version in our submodule? [a75b4ac](https://github.com/NVIDIA/cutlass/tree/a75b4ac483166189a45290783cb0a18af5ff0ea5)
> 

Yes, as far as I could tell.  I did a:

 git submodule update --init recursive 
 
 after cloning this repo.

> Also, please try upgrading MSVC to the latest version. We tested it on Visual Studio 17.11

I am using MSVC 2022 Community Edition, with cl.exe --version reporting:

Compilador de optimización de C/C++ de Microsoft (R) versión 19.40.33812 para x64
(C) Microsoft Corporation. Todos los derechos reservados.

Sorry for it being in Spanish.

**Comment by ggarra13** [comment]
If you mean clang, I have:

$ clang --version
clang version 17.0.3
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\Llvm\x64\bin

**Comment by sxtyzhangzk** [comment]
Our `cl --version` shows `19.41.34123`. You probably need to upgrade your MSVC.

**Comment by ggarra13** [comment]
Upgrading MSVC solves it.  Closed as complete.
