### ISSUE TITLE
FID Misaligned during Flux.1-schnell Reproduction

### ISSUE THREAD

**Issue by NSun-S** [mit-han-lab/nunchaku#60]
Thanks for your awesome work! 

I have been attempting to reproduce the quantization of the Flux.1-schnell and have obtained the following results. It appears that all the metrics are in line with what is presented in the paper, with the exception of the "fid" metric. 

I am unsure if there might be a particular configuration that I have either overlooked or perhaps misaligned during the process. Looking forward for your reply.
```
# before quant
{
  "MJHQ-1024": {
    "with_gt": {
      "clip_iqa": 0.9374287128448486,
      "clip_score": 26.522300720214844,
      "fid": 59.22809264363019,
      "image_reward": 0.9312670520291704
    }
  }
}
# after quant
{
  "MJHQ-1024": {
    "with_gt": {
      "clip_iqa": 0.938270092010498,
      "clip_score": 26.360868453979492,
      "fid": 58.70952959844749,
      "image_reward": 0.91175379300239
    },
    "with_orig": {
      "fid": 32.62904152864269,
      "lpips": 0.2956272065639496,
      "psnr": 17.318588256835938,
      "ssim": 0.6896007657051086
    }
  }
}
```

**Comment by lmxyy** [comment]
To reproduce the results from our paper, please use 5,000 image samples for evaluation. It appears that the current discrepancy is due to an insufficient number of evaluation samples. Increasing the sample size will significantly lower the FID score.
