### ISSUE TITLE
The inference time between svdq-int4-flux.1-dev and flux.1-dev(bf16) is almost the same in comfyui

### ISSUE THREAD

**Issue by YunjieYu** [mit-han-lab/nunchaku#64]
Hi,
First of all, I must admit that **nunchaku** has made a huge contribution to the realm of diffusion models, helping people achieve low-cost and low-latency inference.
When I test the svdq-int4-flux.1-dev in comfyui, I found that the inference time between svdq-int4-flux.1-dev and flux.1-dev(bf16) is almost the same, 10.2s v.s 11.2s.
So I want to know if there are some problems here.
Basic information as below:
> **GPU: A100-SXM4-80GB**
> **CUDA: 12.2**
> **Generation size: (batch size:1, width: 768, height: 1280)**

Note that **I do not use INT4 text encoder to infer**, could this be the resason?

**Comment by YunjieYu** [comment]
I have tested INT4 text encoder to infer. Compared to the previous two sets of settings, the inference time for **svdq-int4-flux.1-dev + INT4 text encoder** is almost the same too (10.2s v.s. 11.2s v.s. 10.4s). Only the GPU inference memory has become less.

**Comment by pyoliu** [comment]
![image](https://github.com/user-attachments/assets/fd51da79-d68e-4129-9ad6-dde22dc7630f)
How did you successfully run on Comfyui?

**Comment by tensorflowt** [comment]
> ![image](https://private-user-images.githubusercontent.com/114060912/398339378-fd51da79-d68e-4129-9ad6-dde22dc7630f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4Njk4MDMsIm5iZiI6MTczNTg2OTUwMywicGF0aCI6Ii8xMTQwNjA5MTIvMzk4MzM5Mzc4LWZkNTFkYTc5LWQ2OGUtNDEyOS05YWQ2LWRkZTIyZGM3NjMwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwM1QwMTU4MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNjJjOGQ0MTU0NDU5YWEwMjU2OTJmM2UyNDA1ZWQxNDc1MmY0MmM0OWZjY2I3NzE0YTcwNWQ2OTI1MmM5YzQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tGlbHwAt7NfZHTTqHb8bLXE3htNP53BY2n_DmxrFX74) How did you successfully run on Comfyui?

目前我在comfyui上跑通了bf16的，int4还有问题，你那边跑通了吗？

**Comment by zhiwei-dong** [comment]
> Hi, First of all, I must admit that **nunchaku** has made a huge contribution to the realm of diffusion models, helping people achieve low-cost and low-latency inference. When I test the svdq-int4-flux.1-dev in comfyui, I found that the inference time between svdq-int4-flux.1-dev and flux.1-dev(bf16) is almost the same, 10.2s v.s 11.2s. So I want to know if there are some problems here. Basic information as below:
> 
> > **GPU: A100-SXM4-80GB**
> > **CUDA: 12.2**
> > **Generation size: (batch size:1, width: 768, height: 1280)**
> 
> Note that **I do not use INT4 text encoder to infer**, could this be the resason?

I came to a similar conclusion as you.
