### ISSUE TITLE
terminate called after throwing an instance of 'CUDAError'

### ISSUE THREAD

**Issue by knishika62** [mit-han-lab/nunchaku#8]
$ python example.py
Loading checkpoint shards: 100%|██████████████████████████████████████| 2/2 [00:00<00:00, 14.15it/s]
Loading pipeline components...:  57%|██████████████████▊              | 4/7 [00:00<00:00,  6.78it/s]You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
Loading pipeline components...: 100%|█████████████████████████████████| 7/7 [00:00<00:00,  9.20it/s]
[2024-11-10 07:05:24.144] [info] Initializing QuantizedFluxModel
[2024-11-10 07:05:24.261] [info] Loading weights from /home/test/.cache/huggingface/hub/models--mit-han-lab--svdquant-models/snapshots/d2a46e82a378ec70e3329a2219ac4331a444a999/svdq-int4-flux.1-schnell.safetensors
[2024-11-10 07:05:24.261] [warning] Unable to pin memory: operation not supported
[2024-11-10 07:05:25.061] [info] Done.
terminate called after throwing an instance of 'CUDAError'
  what():  CUDA error: pointer does not correspond to a registered memory region (at /home/knishika/AI2/work/nunchaku/src/Serialization.cpp:32)
Aborted (core dumped)

Ubuntu 22.04.5 LTS, RTX4090, CUDA Toolkit 12.4, driver is 550-open.

**Comment by knishika62** [comment]
The installation is the same as this.
https://www.reddit.com/r/StableDiffusion/comments/1gmse2o/comment/lw6qaxl/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

**Comment by sxtyzhangzk** [comment]
Hi, please try the latest version and see if it fixes the problem.

**Comment by knishika62** [comment]
it worked! thank you.
