### ISSUE TITLE
width, height MAX 1024px?

### ISSUE THREAD

**Issue by knishika62** [mit-han-lab/nunchaku#9]
FLUX.1 dev and schnell support 2MP(max 1408 x 1408). However, if you enter a value greater than 1024 in run_gradio.py, an error will occur (1024x768 worked without problems).

width = 1040, height = 1024
width = 832, height = 1216

100%|████████████████████████████████████████████████████████████| 25/25 [00:05<00:00,  4.85steps/s]
  0%|                                                                     | 0/25 [00:00<?, ?steps/s]python: /home/knishika/AI2/work/nunchaku/src/pytorch_compat.h:8: void pytorch_compat::TORCH_CHECK(bool, const string&): Assertion `cond' failed.
Aborted (core dumped)

**Comment by lmxyy** [comment]
Could you try 1536x1536 or 1280x1280?

**Comment by knishika62** [comment]
1280x1280 is CUDA OOM.

**Comment by lmxyy** [comment]
I see. How much gpu memory do you have?

**Comment by knishika62** [comment]
RTX 4090 (24GB)

**Comment by knishika62** [comment]
OOM can't be helped, but if you do this(width = 1040, height = 1024 / width = 832, height = 1216) before that, the above error will occur.

**Comment by lmxyy** [comment]
I see. Currently, our engine only supports images with pixel counts that are multiples of 65,536. We will fix this in our next release.

**Comment by lmxyy** [comment]
BTW, you can also use our 4-bit text encoder to address the issues of OOM on your desktop. Just add the option `--use-qencoder`. You may need to install [`deepcompressor`](https://github.com/mit-han-lab/deepcompressor) to enable that for now.
```shell
git clone https://github.com/mit-han-lab/deepcompressor
cd deepcompressor
pip install poetry
poetry install
```
We will remove the dependency in the next release.

**Comment by knishika62** [comment]
>I see. Currently, our engine only supports images with pixel counts that are multiples of 65,536. We will fix this in our next release. You can try width 960, and height 1024.

understood. and 960x1024 OK! thank you.

**Comment by shencuifeng** [comment]
> I see. Currently, our engine only supports images with pixel counts that are multiples of 65,536. We will fix this in our next release. You can try width 960, and height 1024.

Hi, may I ask when will you make the next release?

**Comment by shencuifeng** [comment]
Could you give me some hints about how to solve the image size problems and how to expand the max image size?
